In [ ]:
# Importing libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv('https://raw.githubusercontent.com/mhmmd-nauman/DataSets/master/black-box-models/CP-Nets/wpbc/original%20ds/wpbc%20-%20complete.csv')

#del data['Unnamed: 32']

In [ ]:
index = data.index
number_of_rows = len(index)
print(number_of_rows)

194


In [ ]:
data.head()

Outcome  Time  Mean Radius  Mean Texture  Mean Perimeter  Mean Area  \
0       N    31        18.02         27.60          117.50     1013.0   
1       N    61        17.99         10.38          122.80     1001.0   
2       N   116        21.37         17.44          137.50     1373.0   
3       N   123        11.42         20.38           77.58      386.1   
4       R    27        20.29         14.34          135.10     1297.0   

   Mean Smoothness  Mean Compactness  Mean Concavity  Mean Concave Points  \
0          0.09489            0.1036          0.1086              0.07055   
1          0.11840            0.2776          0.3001              0.14710   
2          0.08836            0.1189          0.1255              0.08180   
3          0.14250            0.2839          0.2414              0.10520   
4          0.10030            0.1328          0.1980              0.10430   

   ...  Worst Perimeter  Worst Area  Worst Smoothness  Worst Compactness  \
0  ...           139.70      1436.0            0.1195             0.1926   
1  ...           184.60      2019.0            0.1622             0.6656   
2  ...           159.10      1949.0            0.1188             0.3449   
3  ...            98.87       567.7            0.2098             0.8663   
4  ...           152.20      1575.0            0.1374             0.2050   

   Worst Concavity  Worst Concave Points  Worst Symmetry  \
0           0.3140                0.1170          0.2677   
1           0.7119                0.2654          0.4601   
2           0.3414                0.2032          0.4334   
3           0.6869                0.2575          0.6638   
4           0.4000                0.1625          0.2364   

   Worst Fractal Dimension  Tumor size  Lymph node status  
0                  0.08113         5.0                  5  
1                  0.11890         3.0                  2  
2                  0.09067         2.5                  0  
3                  0.17300         2.0                  0  
4                  0.07678         3.5                  0  

[5 rows x 34 columns]

In [ ]:
# Encoding categorical data
from sklearn.preprocessing import LabelEncoder
labelencoder_X_1 = LabelEncoder()
y = labelencoder_X_1.fit_transform(data['Outcome'])

In [ ]:
X = data.iloc[:, 1:34].values

In [ ]:
X

array([[3.100e+01, 1.802e+01, 2.760e+01, ..., 8.113e-02, 5.000e+00,
        5.000e+00],
       [6.100e+01, 1.799e+01, 1.038e+01, ..., 1.189e-01, 3.000e+00,
        2.000e+00],
       [1.160e+02, 2.137e+01, 1.744e+01, ..., 9.067e-02, 2.500e+00,
        0.000e+00],
       ...,
       [8.000e+00, 1.544e+01, 3.118e+01, ..., 8.024e-02, 1.500e+00,
        0.000e+00],
       [1.200e+01, 1.717e+01, 2.919e+01, ..., 6.033e-02, 3.700e+00,
        0.000e+00],
       [6.000e+00, 1.670e+01, 2.813e+01, ..., 8.036e-02, 3.500e+00,
        0.000e+00]])

In [ ]:
y

array([0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 0)

#Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
y

array([0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout

In [ ]:
def create_baseline(x_size, y_size):
    # create model
    model = Sequential()
    model.add(Dense(36, input_dim=x_size, kernel_initializer='normal', activation='relu'))
    model.add(Dense(x_size,  activation='relu'))
    model.add(Dense(1, activation='sigmoid'))
    # Compile model. We use the the logarithmic loss function, and the Adam gradient optimizer. mean_squared_error
    model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])
    return model

In [ ]:
# Initialising the ANN
#classifier = Sequential()
model = create_baseline(X.shape[1], 1)

In [ ]:
# Adding the input layer and the first hidden layer
#classifier.add(Dense(3, activation='relu', input_dim=5))
# Adding dropout to prevent overfitting
#classifier.add(Dropout(p=0.1))

In [ ]:
# Adding the output layer
#classifier.add(Dense(1, activation='sigmoid'))

In [ ]:
# Compiling the ANN
#classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
# Fitting the ANN to the Training set
#classifier.fit(X_train, y_train, batch_size=10, epochs=50)
# Long scroll ahead but worth
# The batch size and number of epochs have been set using trial and error. Still looking for more efficient ways. Open to suggestions.
model.fit(X_train, y_train,
    batch_size=20,
    epochs=150,
    #shuffle=True,
    verbose=0 # Change it to 2, if wished to observe execution
    #validation_data=(kc_x_valid, kc_y_valid)
    ) 

In [ ]:
# Predicting the Test set results
#y_pred = classifier.predict(X_test)
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)

In [ ]:
#score = classifier.evaluate(X_test,y_test)
score = model.evaluate(X_test,y_test)
print(score)

2/2 [==============================] - 0s 13ms/step - loss: 0.1922 - accuracy: 0.7797
[0.19215203821659088, 0.7796609997749329]


In [ ]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
Sp = tn / (tn+fp)
Sn = tp/(tp + fn)

In [ ]:
print(cm)
print(Sp)
print(Sn)

[[43  3]
 [10  3]]
0.9347826086956522
0.23076923076923078


In [ ]:
from sklearn.metrics import cohen_kappa_score
cohen_score = cohen_kappa_score(y_test, y_pred)
print(cohen_score)

0.20518134715025904
